# Generated by Django 3.2.8 on 2021-10-08 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Essay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='姓名', max_length=100)),
                ('学号', models.IntegerField(db_column='学号')),
                ('subject', models.TextField(db_column='题目')),
                ('secondary_subject', models.TextField(db_column='副标题')),
                ('context', models.TextField(db_column='正文')),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
