# Generated by Django 3.2.8 on 2021-10-08 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essays', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='essay',
            name='context',
            field=models.TextField(db_column='context'),
        ),
        migrations.AlterField(
            model_name='essay',
            name='name',
            field=models.CharField(db_column='student_name', max_length=100),
        ),
        migrations.AlterField(
            model_name='essay',
            name='secondary_subject',
            field=models.TextField(blank=True, db_column='secondary_subject', null=True),
        ),
        migrations.AlterField(
            model_name='essay',
            name='subject',
            field=models.TextField(blank=True, db_column='subject', null=True),
        ),
        migrations.AlterField(
            model_name='essay',
            name='学号',
            field=models.IntegerField(db_column='student_number'),
        ),
    ]
