# Generated by Django 3.2.8 on 2021-10-08 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essays', '0002_auto_20211008_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='essay',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='essay',
            name='serial_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='essay',
            name='secondary_subject',
            field=models.CharField(blank=True, db_column='secondary_subject', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='essay',
            name='subject',
            field=models.CharField(blank=True, db_column='subject', max_length=100, null=True),
        ),
    ]
