# Generated by Django 3.2.8 on 2021-10-08 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('essays', '0003_auto_20211008_1056'),
    ]

    operations = [
        migrations.RenameField(
            model_name='essay',
            old_name='name',
            new_name='student_name',
        ),
    ]
