# Generated by Django 3.2.8 on 2021-10-08 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essays', '0004_rename_name_essay_student_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='essay',
            old_name='学号',
            new_name='student_no',
        ),
        migrations.AlterField(
            model_name='essay',
            name='pub_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date published'),
        ),
    ]
