# Generated by Django 3.2.8 on 2021-10-08 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essays', '0005_auto_20211008_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='essay',
            name='essay_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
